### ISSUE TITLE
libraries required

### ISSUE THREAD

**Issue by geomaticist** [fairbanks-dot/ldp_scripts#1]
I just realized that the math portion of the LDP scripts use numpy. Which is no big deal. But I doubt numpy is needed for the LambertConformalConic.py script. And I need to pull the math out of the old main script and make a TransverseMercator.py and Obliquemercator.py. I think I should NOT use numpy in them and instead just use the built in library with python. math.

So those three are a little more pure  and can stand alone.

now I may need, or prefer I guess, to use numpy for some of the optimizers. Even those though I bet it was not needed. maybe ... I am probably not even using the numpy power and rather just doing simple list and array sorting. I bet no real need for numpy.

Who cares. The thought really is to make it easier to use the code for someone else.

**Comment by grimm** [comment]
The only issue I can think of that would affect the script by not using
numpy is that the native python math is slow.  Numpy has parts of it
compiled with C or C++ so it's blazing fast.

Jason

**Comment by geomaticist** [comment]
oh that's right ... and we already struggling with speed issues. ok. numpy it is.
